# Generated by BoostInstall.cmake for boost_property_tree-1.83.0

include(CMakeFindDependencyMacro)

find_dependency(boost_any 1.83.0 EXACT)
find_dependency(boost_assert 1.83.0 EXACT)
find_dependency(boost_bind 1.83.0 EXACT)
find_dependency(boost_config 1.83.0 EXACT)
find_dependency(boost_core 1.83.0 EXACT)
find_dependency(boost_format 1.83.0 EXACT)
find_dependency(boost_iterator 1.83.0 EXACT)
find_dependency(boost_mpl 1.83.0 EXACT)
find_dependency(boost_multi_index 1.83.0 EXACT)
find_dependency(boost_optional 1.83.0 EXACT)
find_dependency(boost_range 1.83.0 EXACT)
find_dependency(boost_serialization 1.83.0 EXACT)
find_dependency(boost_static_assert 1.83.0 EXACT)
find_dependency(boost_throw_exception 1.83.0 EXACT)
find_dependency(boost_type_traits 1.83.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_property_tree-targets.cmake")
