# Generated by BoostInstall.cmake for boost_units-1.83.0

include(CMakeFindDependencyMacro)

find_dependency(boost_assert 1.83.0 EXACT)
find_dependency(boost_config 1.83.0 EXACT)
find_dependency(boost_core 1.83.0 EXACT)
find_dependency(boost_integer 1.83.0 EXACT)
find_dependency(boost_io 1.83.0 EXACT)
find_dependency(boost_lambda 1.83.0 EXACT)
find_dependency(boost_math 1.83.0 EXACT)
find_dependency(boost_mpl 1.83.0 EXACT)
find_dependency(boost_preprocessor 1.83.0 EXACT)
find_dependency(boost_static_assert 1.83.0 EXACT)
find_dependency(boost_type_traits 1.83.0 EXACT)
find_dependency(boost_typeof 1.83.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_units-targets.cmake")
