# Generated by BoostInstall.cmake for boost_local_function-1.83.0

include(CMakeFindDependencyMacro)

find_dependency(boost_config 1.83.0 EXACT)
find_dependency(boost_mpl 1.83.0 EXACT)
find_dependency(boost_preprocessor 1.83.0 EXACT)
find_dependency(boost_scope_exit 1.83.0 EXACT)
find_dependency(boost_type_traits 1.83.0 EXACT)
find_dependency(boost_typeof 1.83.0 EXACT)
find_dependency(boost_utility 1.83.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_local_function-targets.cmake")
