# Generated by BoostInstall.cmake for boost_safe_numerics-1.83.0

include(CMakeFindDependencyMacro)

find_dependency(boost_concept_check 1.83.0 EXACT)
find_dependency(boost_config 1.83.0 EXACT)
find_dependency(boost_core 1.83.0 EXACT)
find_dependency(boost_integer 1.83.0 EXACT)
find_dependency(boost_logic 1.83.0 EXACT)
find_dependency(boost_mp11 1.83.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_safe_numerics-targets.cmake")
