# Generated by BoostInstall.cmake for boost_container_hash-1.83.0

include(CMakeFindDependencyMacro)

find_dependency(boost_config 1.83.0 EXACT)
find_dependency(boost_describe 1.83.0 EXACT)
find_dependency(boost_mp11 1.83.0 EXACT)
find_dependency(boost_type_traits 1.83.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_container_hash-targets.cmake")
