# Generated by BoostInstall.cmake for boost_vmd-1.83.0

include(CMakeFindDependencyMacro)

find_dependency(boost_preprocessor 1.83.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_vmd-targets.cmake")
