# Generated by BoostInstall.cmake for boost_redis-1.86.0

if(Boost_VERBOSE OR Boost_DEBUG)
  message(STATUS "Found boost_redis ${boost_redis_VERSION} at ${boost_redis_DIR}")
endif()

include("${CMAKE_CURRENT_LIST_DIR}/boost_redis-targets.cmake")
