# Generated by BoostInstall.cmake for boost_describe-1.83.0

include(CMakeFindDependencyMacro)

find_dependency(boost_mp11 1.83.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_describe-targets.cmake")
