# Generated by BoostInstall.cmake for boost_sort-1.83.0

include(CMakeFindDependencyMacro)

find_dependency(boost_config 1.83.0 EXACT)
find_dependency(boost_core 1.83.0 EXACT)
find_dependency(boost_range 1.83.0 EXACT)
find_dependency(boost_static_assert 1.83.0 EXACT)
find_dependency(boost_type_traits 1.83.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_sort-targets.cmake")
