# Generated by BoostInstall.cmake for boost_assign-1.83.0

include(CMakeFindDependencyMacro)

find_dependency(boost_array 1.83.0 EXACT)
find_dependency(boost_config 1.83.0 EXACT)
find_dependency(boost_core 1.83.0 EXACT)
find_dependency(boost_move 1.83.0 EXACT)
find_dependency(boost_mpl 1.83.0 EXACT)
find_dependency(boost_preprocessor 1.83.0 EXACT)
find_dependency(boost_ptr_container 1.83.0 EXACT)
find_dependency(boost_range 1.83.0 EXACT)
find_dependency(boost_static_assert 1.83.0 EXACT)
find_dependency(boost_throw_exception 1.83.0 EXACT)
find_dependency(boost_tuple 1.83.0 EXACT)
find_dependency(boost_type_traits 1.83.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_assign-targets.cmake")
