# Generated by BoostInstall.cmake for boost_multiprecision-1.83.0

include(CMakeFindDependencyMacro)

find_dependency(boost_assert 1.83.0 EXACT)
find_dependency(boost_config 1.83.0 EXACT)
find_dependency(boost_core 1.83.0 EXACT)
find_dependency(boost_integer 1.83.0 EXACT)
find_dependency(boost_lexical_cast 1.83.0 EXACT)
find_dependency(boost_math 1.83.0 EXACT)
find_dependency(boost_random 1.83.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_multiprecision-targets.cmake")
