# Generated by BoostInstall.cmake for boost_dll-1.83.0

include(CMakeFindDependencyMacro)

find_dependency(boost_assert 1.83.0 EXACT)
find_dependency(boost_config 1.83.0 EXACT)
find_dependency(boost_core 1.83.0 EXACT)
find_dependency(boost_filesystem 1.83.0 EXACT)
find_dependency(boost_function 1.83.0 EXACT)
find_dependency(boost_move 1.83.0 EXACT)
find_dependency(boost_predef 1.83.0 EXACT)
find_dependency(boost_smart_ptr 1.83.0 EXACT)
find_dependency(boost_spirit 1.83.0 EXACT)
find_dependency(boost_static_assert 1.83.0 EXACT)
find_dependency(boost_system 1.83.0 EXACT)
find_dependency(boost_throw_exception 1.83.0 EXACT)
find_dependency(boost_type_index 1.83.0 EXACT)
find_dependency(boost_type_traits 1.83.0 EXACT)
find_dependency(boost_winapi 1.83.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_dll-targets.cmake")
