# Generated by BoostInstall.cmake for boost_poly_collection-1.83.0

include(CMakeFindDependencyMacro)

find_dependency(boost_assert 1.83.0 EXACT)
find_dependency(boost_config 1.83.0 EXACT)
find_dependency(boost_core 1.83.0 EXACT)
find_dependency(boost_iterator 1.83.0 EXACT)
find_dependency(boost_mp11 1.83.0 EXACT)
find_dependency(boost_mpl 1.83.0 EXACT)
find_dependency(boost_type_erasure 1.83.0 EXACT)
find_dependency(boost_type_traits 1.83.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_poly_collection-targets.cmake")
