# Generated by BoostInstall.cmake for boost_process-1.83.0

include(CMakeFindDependencyMacro)

find_dependency(boost_algorithm 1.83.0 EXACT)
find_dependency(boost_asio 1.83.0 EXACT)
find_dependency(boost_config 1.83.0 EXACT)
find_dependency(boost_core 1.83.0 EXACT)
find_dependency(boost_filesystem 1.83.0 EXACT)
find_dependency(boost_fusion 1.83.0 EXACT)
find_dependency(boost_iterator 1.83.0 EXACT)
find_dependency(boost_move 1.83.0 EXACT)
find_dependency(boost_optional 1.83.0 EXACT)
find_dependency(boost_system 1.83.0 EXACT)
find_dependency(boost_tokenizer 1.83.0 EXACT)
find_dependency(boost_type_index 1.83.0 EXACT)
find_dependency(boost_winapi 1.83.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_process-targets.cmake")
