# Generated by BoostInstall.cmake for boost_assert-1.83.0

include(CMakeFindDependencyMacro)

find_dependency(boost_config 1.83.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_assert-targets.cmake")
