# Generated by BoostInstall.cmake for boost_format-1.83.0

include(CMakeFindDependencyMacro)

find_dependency(boost_assert 1.83.0 EXACT)
find_dependency(boost_config 1.83.0 EXACT)
find_dependency(boost_core 1.83.0 EXACT)
find_dependency(boost_optional 1.83.0 EXACT)
find_dependency(boost_smart_ptr 1.83.0 EXACT)
find_dependency(boost_throw_exception 1.83.0 EXACT)
find_dependency(boost_utility 1.83.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_format-targets.cmake")
