# Generated by BoostInstall.cmake for boost_outcome-1.83.0

include(CMakeFindDependencyMacro)

find_dependency(boost_config 1.83.0 EXACT)
find_dependency(boost_exception 1.83.0 EXACT)
find_dependency(boost_system 1.83.0 EXACT)
find_dependency(boost_throw_exception 1.83.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_outcome-targets.cmake")
