# Generated by BoostInstall.cmake for boost_filesystem-1.83.0

include(CMakeFindDependencyMacro)

find_dependency(boost_assert 1.83.0 EXACT)
find_dependency(boost_config 1.83.0 EXACT)
find_dependency(boost_container_hash 1.83.0 EXACT)
find_dependency(boost_core 1.83.0 EXACT)
find_dependency(boost_detail 1.83.0 EXACT)
find_dependency(boost_io 1.83.0 EXACT)
find_dependency(boost_iterator 1.83.0 EXACT)
find_dependency(boost_smart_ptr 1.83.0 EXACT)
find_dependency(boost_system 1.83.0 EXACT)
find_dependency(boost_type_traits 1.83.0 EXACT)
find_dependency(boost_predef 1.83.0 EXACT)
find_dependency(boost_atomic 1.83.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_filesystem-targets.cmake")
