# Generated by BoostInstall.cmake for boost_lambda-1.83.0

include(CMakeFindDependencyMacro)

find_dependency(boost_bind 1.83.0 EXACT)
find_dependency(boost_config 1.83.0 EXACT)
find_dependency(boost_core 1.83.0 EXACT)
find_dependency(boost_detail 1.83.0 EXACT)
find_dependency(boost_iterator 1.83.0 EXACT)
find_dependency(boost_mpl 1.83.0 EXACT)
find_dependency(boost_preprocessor 1.83.0 EXACT)
find_dependency(boost_tuple 1.83.0 EXACT)
find_dependency(boost_type_traits 1.83.0 EXACT)
find_dependency(boost_utility 1.83.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_lambda-targets.cmake")
