# Generated by BoostInstall.cmake for boost_ptr_container-1.83.0

include(CMakeFindDependencyMacro)

find_dependency(boost_array 1.83.0 EXACT)
find_dependency(boost_assert 1.83.0 EXACT)
find_dependency(boost_circular_buffer 1.83.0 EXACT)
find_dependency(boost_config 1.83.0 EXACT)
find_dependency(boost_core 1.83.0 EXACT)
find_dependency(boost_iterator 1.83.0 EXACT)
find_dependency(boost_mpl 1.83.0 EXACT)
find_dependency(boost_range 1.83.0 EXACT)
find_dependency(boost_smart_ptr 1.83.0 EXACT)
find_dependency(boost_static_assert 1.83.0 EXACT)
find_dependency(boost_type_traits 1.83.0 EXACT)
find_dependency(boost_unordered 1.83.0 EXACT)
find_dependency(boost_utility 1.83.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_ptr_container-targets.cmake")
