# Generated by BoostInstall.cmake for boost_phoenix-1.83.0

include(CMakeFindDependencyMacro)

find_dependency(boost_assert 1.83.0 EXACT)
find_dependency(boost_bind 1.83.0 EXACT)
find_dependency(boost_config 1.83.0 EXACT)
find_dependency(boost_core 1.83.0 EXACT)
find_dependency(boost_function 1.83.0 EXACT)
find_dependency(boost_fusion 1.83.0 EXACT)
find_dependency(boost_mpl 1.83.0 EXACT)
find_dependency(boost_predef 1.83.0 EXACT)
find_dependency(boost_preprocessor 1.83.0 EXACT)
find_dependency(boost_proto 1.83.0 EXACT)
find_dependency(boost_range 1.83.0 EXACT)
find_dependency(boost_smart_ptr 1.83.0 EXACT)
find_dependency(boost_type_traits 1.83.0 EXACT)
find_dependency(boost_utility 1.83.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_phoenix-targets.cmake")
