# Generated by BoostInstall.cmake for boost_convert-1.83.0

include(CMakeFindDependencyMacro)

find_dependency(boost_config 1.83.0 EXACT)
find_dependency(boost_core 1.83.0 EXACT)
find_dependency(boost_function_types 1.83.0 EXACT)
find_dependency(boost_lexical_cast 1.83.0 EXACT)
find_dependency(boost_math 1.83.0 EXACT)
find_dependency(boost_mpl 1.83.0 EXACT)
find_dependency(boost_optional 1.83.0 EXACT)
find_dependency(boost_parameter 1.83.0 EXACT)
find_dependency(boost_range 1.83.0 EXACT)
find_dependency(boost_spirit 1.83.0 EXACT)
find_dependency(boost_type_traits 1.83.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_convert-targets.cmake")
