# Generated by BoostInstall.cmake for boost_numeric_interval-1.83.0

include(CMakeFindDependencyMacro)

find_dependency(boost_config 1.83.0 EXACT)
find_dependency(boost_detail 1.83.0 EXACT)
find_dependency(boost_logic 1.83.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_numeric_interval-targets.cmake")
