# Generated by BoostInstall.cmake for boost_flyweight-1.83.0

include(CMakeFindDependencyMacro)

find_dependency(boost_assert 1.83.0 EXACT)
find_dependency(boost_config 1.83.0 EXACT)
find_dependency(boost_container_hash 1.83.0 EXACT)
find_dependency(boost_core 1.83.0 EXACT)
find_dependency(boost_detail 1.83.0 EXACT)
find_dependency(boost_interprocess 1.83.0 EXACT)
find_dependency(boost_mpl 1.83.0 EXACT)
find_dependency(boost_multi_index 1.83.0 EXACT)
find_dependency(boost_parameter 1.83.0 EXACT)
find_dependency(boost_preprocessor 1.83.0 EXACT)
find_dependency(boost_smart_ptr 1.83.0 EXACT)
find_dependency(boost_throw_exception 1.83.0 EXACT)
find_dependency(boost_type_traits 1.83.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_flyweight-targets.cmake")
